name: tflite_object_detection_sample
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # TODO 3: add the following dependencies
  get: ^4.6.6
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  flutter_tflite: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # TODO 4: add the assets directory that contains the model and its labels
  assets:
    - assets/